from langchain_core.tools import BaseTool

from cairn.tools.combat import (
    add_combatant,
    add_exhaustion,
    advance_turn,
    apply_aoe_damage,
    apply_condition,
    apply_damage,
    apply_effect,
    apply_healing,
    apply_temp_hp,
    award_xp,
    cast_concentration_spell,
    end_combat,
    remove_combatant,
    remove_condition,
    remove_effect,
    remove_exhaustion,
    resolve_contest,
    roll_death_save,
    roll_initiative,
    roll_saving_throw,
    roll_skill_check,
    stabilize_character,
    start_combat,
)
from cairn.tools.dice import roll_ability_scores, roll_d20, roll_damage
from cairn.tools.game_state import (
    fetch_combat_context,
    get_character,
    get_combat_state,
    get_npc,
    get_party,
    loot_item,
)
from cairn.tools.inspiration import grant_inspiration
from cairn.tools.resources import (
    apply_long_rest,
    apply_short_rest,
    consume_spell_slot,
    drop_concentration,
    restore_resource,
    restore_spell_slot,
    roll_concentration_check,
    roll_hit_die,
    set_concentration,
    spend_movement,
    use_action,
    use_bonus_action,
    use_reaction,
    use_resource,
)
from cairn.tools.srd import (
    list_feats,
    list_spells_for_class,
    lookup_class,
    lookup_condition,
    lookup_feat,
    lookup_feature,
    lookup_monster,
    lookup_race,
    lookup_spell,
    lookup_subclass,
    lookup_trait,
    lookup_weapon,
)

ALL_TOOLS: list[BaseTool] = [
    # Dice
    roll_d20,
    roll_damage,
    roll_ability_scores,
    # SRD lookups
    lookup_spell,
    lookup_monster,
    lookup_condition,
    lookup_weapon,
    lookup_race,
    lookup_class,
    lookup_feature,
    lookup_feat,
    list_feats,
    lookup_trait,
    lookup_subclass,
    list_spells_for_class,
    # Game state reads
    get_character,
    get_npc,
    get_party,
    get_combat_state,
    loot_item,
    # Combat mutations
    start_combat,
    end_combat,
    add_combatant,
    remove_combatant,
    apply_damage,
    apply_aoe_damage,
    apply_temp_hp,
    apply_healing,
    apply_condition,
    remove_condition,
    roll_death_save,
    stabilize_character,
    roll_initiative,
    roll_saving_throw,
    roll_skill_check,
    resolve_contest,
    advance_turn,
    apply_effect,
    remove_effect,
    cast_concentration_spell,
    award_xp,
    add_exhaustion,
    remove_exhaustion,
    grant_inspiration,
    # Resource & economy
    consume_spell_slot,
    restore_spell_slot,
    use_resource,
    restore_resource,
    set_concentration,
    drop_concentration,
    roll_concentration_check,
    use_action,
    use_bonus_action,
    use_reaction,
    spend_movement,
    # Rests
    apply_short_rest,
    apply_long_rest,
    roll_hit_die,
]

# Subset for combat agents — excludes state reads injected into prompts directly
COMBAT_TOOLS: list[BaseTool] = [
    roll_d20,
    roll_damage,
    lookup_spell,
    lookup_weapon,
    lookup_monster,
    lookup_condition,
    lookup_feature,
    get_npc,
    add_combatant,
    remove_combatant,
    apply_damage,
    apply_aoe_damage,
    apply_temp_hp,
    apply_healing,
    apply_condition,
    remove_condition,
    roll_death_save,
    stabilize_character,
    roll_initiative,
    roll_saving_throw,
    roll_skill_check,
    resolve_contest,
    advance_turn,
    add_exhaustion,
    remove_exhaustion,
    grant_inspiration,
    end_combat,
    loot_item,
    apply_effect,
    remove_effect,
    cast_concentration_spell,
    consume_spell_slot,
    restore_spell_slot,
    use_resource,
    restore_resource,
    set_concentration,
    drop_concentration,
    roll_concentration_check,
    use_action,
    use_bonus_action,
    use_reaction,
    spend_movement,
]

__all__ = ["ALL_TOOLS", "COMBAT_TOOLS", "fetch_combat_context", "loot_item"]
