"""add sessions turns characters npcs locations

Revision ID: 02e02602f1a0
Revises: 806c1a18faee
Create Date: 2026-04-29 08:45:08.178628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02e02602f1a0'
down_revision: Union[str, Sequence[str], None] = '806c1a18faee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_campaign_id'), 'characters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('connections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_campaign_id'), 'locations', ['campaign_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_campaign_id'), 'sessions', ['campaign_id'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('personality', sa.String(), nullable=False),
    sa.Column('voice_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_campaign_id'), 'npcs', ['campaign_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('player_input', sa.String(), nullable=False),
    sa.Column('dm_response', sa.String(), nullable=True),
    sa.Column('dice_rolls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checkpoint_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_npcs_campaign_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_sessions_campaign_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_locations_campaign_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_campaign_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
