"""combat_foundation

Revision ID: 038c74c91910
Revises: cce7a6296d31
Create Date: 2026-05-04 14:14:36.305696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '038c74c91910'
down_revision: Union[str, Sequence[str], None] = 'cce7a6296d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'character_id', name='uq_session_character')
    )
    op.create_index(op.f('ix_session_characters_session_id'), 'session_characters', ['session_id'], unique=False)
    op.add_column('locations', sa.Column('zones', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('sessions', sa.Column('current_location_id', sa.Uuid(), nullable=True))
    op.add_column('sessions', sa.Column('combat_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('sessions', sa.Column('combat_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key('fk_sessions_current_location_id_locations', 'sessions', 'locations', ['current_location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sessions_current_location_id_locations', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'combat_state')
    op.drop_column('sessions', 'combat_active')
    op.drop_column('sessions', 'current_location_id')
    op.drop_column('locations', 'zones')
    op.drop_index(op.f('ix_session_characters_session_id'), table_name='session_characters')
    op.drop_table('session_characters')
    # ### end Alembic commands ###
