"""add subrace to characters, apply racial ability bonuses

Revision ID: 049fe0d5a950
Revises: 9c6088bd01e3
Create Date: 2026-05-09 16:39:16.046285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049fe0d5a950'
down_revision: Union[str, Sequence[str], None] = '9c6088bd01e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('subrace', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'subrace')
    # ### end Alembic commands ###
