"""add is_dead to characters

Revision ID: 04a508f7a8cc
Revises: e8ca771f3ce8
Create Date: 2026-05-08 23:16:40.962910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a508f7a8cc'
down_revision: Union[str, Sequence[str], None] = 'e8ca771f3ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_dead', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_dead')
    # ### end Alembic commands ###
