"""cascade campaign runtime deletion

Revision ID: 1df3aa63957f
Revises: 1eedface5056
Create Date: 2026-07-15 07:40:57.194251

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1df3aa63957f"
down_revision: str | Sequence[str] | None = "1eedface5056"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('characters_campaign_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(
        op.f('characters_campaign_id_fkey'), 'characters', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint(op.f('sessions_campaign_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(
        op.f('sessions_campaign_id_fkey'), 'sessions', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint(op.f('turns_session_id_fkey'), 'turns', type_='foreignkey')
    op.create_foreign_key(
        op.f('turns_session_id_fkey'), 'turns', 'sessions', ['session_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('turns_session_id_fkey'), 'turns', type_='foreignkey')
    op.create_foreign_key(op.f('turns_session_id_fkey'), 'turns', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('sessions_campaign_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_campaign_id_fkey'), 'sessions', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(op.f('characters_campaign_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_campaign_id_fkey'), 'characters', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
