"""add_cascade_delete_to_npcs_campaign_fk

Revision ID: 3aef6507f003
Revises: 5a1706bbefc2
Create Date: 2026-05-02 11:31:50.524367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aef6507f003'
down_revision: Union[str, Sequence[str], None] = '5a1706bbefc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('npcs_campaign_id_fkey'), 'npcs', type_='foreignkey')
    op.create_foreign_key(op.f('npcs_campaign_id_fkey'), 'npcs', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('npcs_campaign_id_fkey'), 'npcs', type_='foreignkey')
    op.create_foreign_key(op.f('npcs_campaign_id_fkey'), 'npcs', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
