"""add turn events column

Revision ID: 4167dd600d26
Revises: 4ac56aed3e83
Create Date: 2026-05-08 22:04:25.518887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4167dd600d26'
down_revision: Union[str, Sequence[str], None] = '4ac56aed3e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'events')
    # ### end Alembic commands ###
