"""add_companion_fields_to_characters

Revision ID: 4ac56aed3e83
Revises: ae736ad8dc08
Create Date: 2026-05-05 22:33:19.861704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac56aed3e83'
down_revision: Union[str, Sequence[str], None] = 'ae736ad8dc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('is_companion', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('characters', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('personality', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('voice_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_traits')
    op.drop_column('characters', 'personality')
    op.drop_column('characters', 'bio')
    op.drop_column('characters', 'is_companion')
    # ### end Alembic commands ###
