"""scene director handoffs, concentration jsonb, scene_id not null

Revision ID: 518789d78afb
Revises: af00bfba941f
Create Date: 2026-06-27 22:26:13.129082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '518789d78afb'
down_revision: Union[str, Sequence[str], None] = 'af00bfba941f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # scene_id becomes NOT NULL. Slice 5 left it nullable and never populated it, so any
    # existing turns/sessions are unplayable scaffolding — nuke them (pre-launch posture).
    op.execute("DELETE FROM turns")
    op.execute("DELETE FROM sessions")

    op.add_column('characters', sa.Column('created_from_premade_id', sa.Uuid(), nullable=True))
    # concentration was a bare spell-name string; the new JSONB shape can't parse it, so
    # null existing values (combat in flight isn't persisted across this migration anyway).
    op.alter_column('characters', 'concentration',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='NULL::jsonb')
    op.create_foreign_key(op.f('fk_characters_created_from_premade_id_premade_characters'), 'characters', 'premade_characters', ['created_from_premade_id'], ['id'], ondelete='SET NULL')
    op.alter_column('npcs', 'concentration',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='NULL::jsonb')
    op.add_column('sessions', sa.Column('pending_transition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('pending_recovery', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('turns', 'scene_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_turns_scene_id'), 'turns', ['scene_id'], unique=False)
    op.drop_constraint(op.f('fk_turns_scene_id_scenes'), 'turns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_turns_scene_id_scenes'), 'turns', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_turns_scene_id_scenes'), 'turns', type_='foreignkey')
    op.create_foreign_key(op.f('fk_turns_scene_id_scenes'), 'turns', 'scenes', ['scene_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_turns_scene_id'), table_name='turns')
    op.alter_column('turns', 'scene_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('sessions', 'pending_recovery')
    op.drop_column('sessions', 'pending_transition')
    op.alter_column('npcs', 'concentration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='NULL::varchar')
    op.drop_constraint(op.f('fk_characters_created_from_premade_id_premade_characters'), 'characters', type_='foreignkey')
    op.alter_column('characters', 'concentration',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='NULL::varchar')
    op.drop_column('characters', 'created_from_premade_id')
    # ### end Alembic commands ###
