"""cascade_delete_locations

Revision ID: 5511ba4f0775
Revises: 038c74c91910
Create Date: 2026-05-04 14:17:43.872980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5511ba4f0775'
down_revision: Union[str, Sequence[str], None] = '038c74c91910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_campaign_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key('fk_locations_campaign_id_campaigns', 'locations', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_locations_campaign_id_campaigns', 'locations', type_='foreignkey')
    op.create_foreign_key('locations_campaign_id_fkey', 'locations', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###
