"""add tool_proficiencies to characters and npcs

Revision ID: 59b7f00d4ebf
Revises: 04a508f7a8cc
Create Date: 2026-05-08 23:41:10.932365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b7f00d4ebf'
down_revision: Union[str, Sequence[str], None] = '04a508f7a8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('tool_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('npcs', sa.Column('tool_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'tool_proficiencies')
    op.drop_column('characters', 'tool_proficiencies')
    # ### end Alembic commands ###
