"""expand npc table with combat fields

Revision ID: 5a1706bbefc2
Revises: ce0d579374c6
Create Date: 2026-05-02 11:24:43.430190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a1706bbefc2'
down_revision: Union[str, Sequence[str], None] = 'ce0d579374c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('disposition', sa.String(), nullable=False))
    op.add_column('npcs', sa.Column('ac', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('max_hp', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('current_hp', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('speed', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('cr', sa.Float(), nullable=False))
    op.add_column('npcs', sa.Column('xp_value', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('stat_block', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'conditions')
    op.drop_column('npcs', 'stat_block')
    op.drop_column('npcs', 'xp_value')
    op.drop_column('npcs', 'cr')
    op.drop_column('npcs', 'speed')
    op.drop_column('npcs', 'current_hp')
    op.drop_column('npcs', 'max_hp')
    op.drop_column('npcs', 'ac')
    op.drop_column('npcs', 'disposition')
    # ### end Alembic commands ###
