"""add armor and weapon proficiencies to characters and npcs

Revision ID: 6ab4ffdfb20e
Revises: f6589a7a1746
Create Date: 2026-05-09 22:18:38.280272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ab4ffdfb20e'
down_revision: Union[str, Sequence[str], None] = 'f6589a7a1746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('armor_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('characters', sa.Column('weapon_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('npcs', sa.Column('armor_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('npcs', sa.Column('weapon_proficiencies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'weapon_proficiencies')
    op.drop_column('npcs', 'armor_proficiencies')
    op.drop_column('characters', 'weapon_proficiencies')
    op.drop_column('characters', 'armor_proficiencies')
    # ### end Alembic commands ###
