"""add feats to characters and npcs

Revision ID: 8fb1348809e8
Revises: 4167dd600d26
Create Date: 2026-05-08 22:22:22.335238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb1348809e8'
down_revision: Union[str, Sequence[str], None] = '4167dd600d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('feats', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('npcs', sa.Column('feats', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'feats')
    op.drop_column('characters', 'feats')
    # ### end Alembic commands ###
