"""rename stats to ability scores, add character status

Revision ID: 9c6088bd01e3
Revises: 59b7f00d4ebf
Create Date: 2026-05-09 16:15:54.186607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c6088bd01e3'
down_revision: Union[str, Sequence[str], None] = '59b7f00d4ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('characters', sa.Column('ability_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('characters', 'is_dead')
    op.drop_column('characters', 'stats')
    op.add_column('npcs', sa.Column('ability_scores', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('npcs', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('npcs', 'ability_scores')
    op.add_column('characters', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('is_dead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('characters', 'ability_scores')
    op.drop_column('characters', 'status')
    # ### end Alembic commands ###
