"""align_creature_schema

Revision ID: a3f226096bb3
Revises: e098d3e7c84d
Create Date: 2026-05-04 22:13:55.445915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3f226096bb3'
down_revision: Union[str, Sequence[str], None] = 'e098d3e7c84d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('cr', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('characters', sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('npcs', sa.Column('hp', sa.Integer(), nullable=False, server_default='1'))
    op.drop_column('npcs', 'current_hp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('current_hp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('npcs', 'hp')
    op.drop_column('characters', 'conditions')
    op.drop_column('characters', 'cr')
    # ### end Alembic commands ###
