"""npc and companion narrative profiles

Revision ID: ac6e41507fc3
Revises: 518789d78afb
Create Date: 2026-07-05 21:12:54.653289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac6e41507fc3'
down_revision: Union[str, Sequence[str], None] = '518789d78afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_templates', sa.Column('world_characters', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('characters', sa.Column('narrative_profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('characters', 'bio')
    op.drop_column('characters', 'personality')
    op.drop_column('characters', 'voice_traits')
    op.add_column('npcs', sa.Column('narrative_profile', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('npcs', sa.Column('tier', sa.String(), server_default='background', nullable=False))
    op.add_column('npcs', sa.Column('dialogue_exchange_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('npcs', sa.Column('recruitable', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('npcs', sa.Column('companion_sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('npcs', sa.Column('recruitment_condition', sa.String(), nullable=True))
    op.drop_column('npcs', 'bio')
    op.drop_column('npcs', 'personality')
    op.drop_column('npcs', 'voice_traits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('voice_traits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('npcs', sa.Column('personality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('npcs', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('npcs', 'recruitment_condition')
    op.drop_column('npcs', 'companion_sheet')
    op.drop_column('npcs', 'recruitable')
    op.drop_column('npcs', 'dialogue_exchange_count')
    op.drop_column('npcs', 'tier')
    op.drop_column('npcs', 'narrative_profile')
    op.add_column('characters', sa.Column('voice_traits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('personality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('bio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('characters', 'narrative_profile')
    op.drop_column('campaign_templates', 'world_characters')
    # ### end Alembic commands ###
