"""world restructure: worlds, templates, premades, scenes, campaign + character + session schema

Revision ID: af00bfba941f
Revises: dad55f4ab35e
Create Date: 2026-05-22 10:01:35.205622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af00bfba941f'
down_revision: Union[str, Sequence[str], None] = 'dad55f4ab35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('calendar', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_worlds_key')
    )
    op.create_index(op.f('ix_worlds_key'), 'worlds', ['key'], unique=False)
    op.create_table('campaign_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('premise', sa.String(), nullable=False),
    sa.Column('acts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('always_on_lore_keys', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_campaign_templates_key')
    )
    op.create_index(op.f('ix_campaign_templates_key'), 'campaign_templates', ['key'], unique=False)
    op.create_index(op.f('ix_campaign_templates_world_id'), 'campaign_templates', ['world_id'], unique=False)
    op.create_table('world_lore_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('always_on', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key', name='uq_world_lore_chunks_world_key')
    )
    op.create_index(op.f('ix_world_lore_chunks_category'), 'world_lore_chunks', ['category'], unique=False)
    op.create_index(op.f('ix_world_lore_chunks_world_id'), 'world_lore_chunks', ['world_id'], unique=False)
    op.create_table('premade_characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('sheet', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['campaign_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'key', name='uq_premade_characters_template_key')
    )
    op.create_index(op.f('ix_premade_characters_template_id'), 'premade_characters', ['template_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('act_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scene_mode', sa.String(), server_default='exploration', nullable=False),
    sa.Column('safety_level', sa.String(), server_default='safe', nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_campaign_id'), 'scenes', ['campaign_id'], unique=False)
    op.drop_index(op.f('ix_party_members_session_id'), table_name='party_members')
    op.drop_table('party_members')
    op.add_column('campaigns', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('campaigns', sa.Column('current_act_index', sa.Integer(), server_default='0', nullable=False))
    op.add_column('campaigns', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('campaigns', sa.Column('member_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.alter_column('campaigns', 'template_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='template_id::uuid')
    op.create_index(op.f('ix_campaigns_template_id'), 'campaigns', ['template_id'], unique=False)
    op.create_foreign_key(
        'fk_campaigns_template_id_campaign_templates', 'campaigns', 'campaign_templates',
        ['template_id'], ['id'], ondelete='RESTRICT',
    )
    op.add_column('characters', sa.Column('classes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('characters', sa.Column('has_inspiration', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('characters', sa.Column('companion_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('characters', 'class')
    op.drop_column('characters', 'subclass')
    op.add_column('sessions', sa.Column('last_day_summarized', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sessions', sa.Column('rng_seed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('turns', sa.Column('scene_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_turns_scene_id_scenes', 'turns', 'scenes', ['scene_id'], ['id'], ondelete='SET NULL')
    op.add_column('world_bible_entries', sa.Column('revealed_at_turn_id', sa.Uuid(), nullable=True))
    op.add_column('world_bible_entries', sa.Column('day_index', sa.Integer(), nullable=True))
    op.add_column('world_bible_entries', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(
        'fk_world_bible_entries_revealed_at_turn_id_turns', 'world_bible_entries', 'turns',
        ['revealed_at_turn_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_world_bible_entries_revealed_at_turn_id_turns', 'world_bible_entries', type_='foreignkey')
    op.drop_column('world_bible_entries', 'embedding')
    op.drop_column('world_bible_entries', 'day_index')
    op.drop_column('world_bible_entries', 'revealed_at_turn_id')
    op.drop_constraint('fk_turns_scene_id_scenes', 'turns', type_='foreignkey')
    op.drop_column('turns', 'scene_id')
    op.drop_column('sessions', 'rng_seed')
    op.drop_column('sessions', 'last_day_summarized')
    op.add_column('characters', sa.Column('subclass', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('class', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('characters', 'companion_meta')
    op.drop_column('characters', 'has_inspiration')
    op.drop_column('characters', 'classes')
    op.drop_constraint('fk_campaigns_template_id_campaign_templates', 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_template_id'), table_name='campaigns')
    op.alter_column('campaigns', 'template_id',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='template_id::text')
    op.drop_column('campaigns', 'member_ids')
    op.drop_column('campaigns', 'settings')
    op.drop_column('campaigns', 'current_act_index')
    op.drop_column('campaigns', 'status')
    op.create_table('party_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_party_members_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_party_members_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_members')),
    sa.UniqueConstraint('session_id', 'character_id', name=op.f('uq_party_member'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_party_members_session_id'), 'party_members', ['session_id'], unique=False)
    op.drop_index(op.f('ix_scenes_campaign_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_premade_characters_template_id'), table_name='premade_characters')
    op.drop_table('premade_characters')
    op.drop_index(op.f('ix_world_lore_chunks_world_id'), table_name='world_lore_chunks')
    op.drop_index(op.f('ix_world_lore_chunks_category'), table_name='world_lore_chunks')
    op.drop_table('world_lore_chunks')
    op.drop_index(op.f('ix_campaign_templates_world_id'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_key'), table_name='campaign_templates')
    op.drop_table('campaign_templates')
    op.drop_index(op.f('ix_worlds_key'), table_name='worlds')
    op.drop_table('worlds')
    # ### end Alembic commands ###
