"""add scene depth and pacing state columns

Revision ID: b155b3d256c7
Revises: ac6e41507fc3
Create Date: 2026-07-08 22:45:43.894498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b155b3d256c7'
down_revision: Union[str, Sequence[str], None] = 'ac6e41507fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('authored', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('scenes', sa.Column('beat_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scenes', sa.Column('tension_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scenes', sa.Column('mood', sa.String(), server_default='quiet', nullable=False))
    op.add_column('scenes', sa.Column('last_revelation_at_turn', sa.Integer(), nullable=True))
    op.add_column('scenes', sa.Column('discovered_facts', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('scenes', sa.Column('unresolved_threads', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('scenes', sa.Column('npcs_present', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('scenes', sa.Column('scene_progress_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'scene_progress_summary')
    op.drop_column('scenes', 'npcs_present')
    op.drop_column('scenes', 'unresolved_threads')
    op.drop_column('scenes', 'discovered_facts')
    op.drop_column('scenes', 'last_revelation_at_turn')
    op.drop_column('scenes', 'mood')
    op.drop_column('scenes', 'tension_level')
    op.drop_column('scenes', 'beat_count')
    op.drop_column('scenes', 'authored')
    # ### end Alembic commands ###
