"""add_world_bible_entries

Revision ID: cce7a6296d31
Revises: dd69952278ca
Create Date: 2026-05-04 13:26:03.633756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce7a6296d31'
down_revision: Union[str, Sequence[str], None] = 'dd69952278ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_bible_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('source_turn_id', sa.Uuid(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_turn_id'], ['turns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'type', 'key', name='uq_entry_campaign_type_key')
    )
    op.create_index(op.f('ix_world_bible_entries_campaign_id'), 'world_bible_entries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_world_bible_entries_namespace'), 'world_bible_entries', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_bible_entries_namespace'), table_name='world_bible_entries')
    op.drop_index(op.f('ix_world_bible_entries_campaign_id'), table_name='world_bible_entries')
    op.drop_table('world_bible_entries')
    # ### end Alembic commands ###
