"""add prepared_spells to characters and in_game_hours_elapsed to sessions

Revision ID: dad55f4ab35e
Revises: 628b8bdfe791
Create Date: 2026-05-21 17:31:44.388279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad55f4ab35e'
down_revision: Union[str, Sequence[str], None] = '628b8bdfe791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('prepared_spells', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sessions', sa.Column('in_game_hours_elapsed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'in_game_hours_elapsed')
    op.drop_column('characters', 'prepared_spells')
    # ### end Alembic commands ###
