"""align_npc_with_character_fields

Revision ID: dd69952278ca
Revises: 3aef6507f003
Create Date: 2026-05-02 11:38:30.238308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd69952278ca'
down_revision: Union[str, Sequence[str], None] = '3aef6507f003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('race', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('class', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('subclass', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('background', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('alignment', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('level', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('portrait_url', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('temp_hp', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('death_save_successes', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('death_save_failures', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('proficiency_bonus', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('initiative', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('passive_perception', sa.Integer(), nullable=False))
    op.add_column('npcs', sa.Column('spellcasting_ability', sa.String(), nullable=True))
    op.add_column('npcs', sa.Column('spell_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('npcs', sa.Column('spells_known', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('saving_throw_proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('skill_proficiencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('npcs', sa.Column('currency', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('npcs', 'stat_block')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('stat_block', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('npcs', 'currency')
    op.drop_column('npcs', 'inventory')
    op.drop_column('npcs', 'features')
    op.drop_column('npcs', 'skill_proficiencies')
    op.drop_column('npcs', 'saving_throw_proficiencies')
    op.drop_column('npcs', 'stats')
    op.drop_column('npcs', 'spells_known')
    op.drop_column('npcs', 'spell_slots')
    op.drop_column('npcs', 'spellcasting_ability')
    op.drop_column('npcs', 'passive_perception')
    op.drop_column('npcs', 'initiative')
    op.drop_column('npcs', 'proficiency_bonus')
    op.drop_column('npcs', 'death_save_failures')
    op.drop_column('npcs', 'death_save_successes')
    op.drop_column('npcs', 'temp_hp')
    op.drop_column('npcs', 'portrait_url')
    op.drop_column('npcs', 'level')
    op.drop_column('npcs', 'alignment')
    op.drop_column('npcs', 'background')
    op.drop_column('npcs', 'subclass')
    op.drop_column('npcs', 'class')
    op.drop_column('npcs', 'race')
    # ### end Alembic commands ###
