"""rename_session_characters_to_party_members

Revision ID: e098d3e7c84d
Revises: 5511ba4f0775
Create Date: 2026-05-04 14:25:08.716689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e098d3e7c84d'
down_revision: Union[str, Sequence[str], None] = '5511ba4f0775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_party_members_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_party_members_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_party_members')),
    sa.UniqueConstraint('session_id', 'character_id', name='uq_party_member')
    )
    op.create_index(op.f('ix_party_members_session_id'), 'party_members', ['session_id'], unique=False)
    op.drop_index(op.f('ix_session_characters_session_id'), table_name='session_characters')
    op.drop_table('session_characters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_characters',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('session_characters_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('session_characters_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_characters_pkey')),
    sa.UniqueConstraint('session_id', 'character_id', name=op.f('uq_session_character'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_session_characters_session_id'), 'session_characters', ['session_id'], unique=False)
    op.drop_index(op.f('ix_party_members_session_id'), table_name='party_members')
    op.drop_table('party_members')
    # ### end Alembic commands ###
