"""add hit dice fields to characters

Revision ID: e8ca771f3ce8
Revises: 8fb1348809e8
Create Date: 2026-05-08 23:10:51.510046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8ca771f3ce8'
down_revision: Union[str, Sequence[str], None] = '8fb1348809e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('hit_die_size', sa.Integer(), server_default='8', nullable=False))
    op.add_column('characters', sa.Column('hit_dice_remaining', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'hit_dice_remaining')
    op.drop_column('characters', 'hit_die_size')
    # ### end Alembic commands ###
