"""add concentration to npcs

Revision ID: f6589a7a1746
Revises: 049fe0d5a950
Create Date: 2026-05-09 16:48:45.585201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6589a7a1746'
down_revision: Union[str, Sequence[str], None] = '049fe0d5a950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npcs', sa.Column('concentration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npcs', 'concentration')
    # ### end Alembic commands ###
